default: &defaults
  parallelism: 1
  working_directory: ~/my-project

k6_performance_tests: &k6_performance_tests
  run:
    name: Running k6 tests
    # Download the k6 docker image. Alternatively, download the k6 release binary
    # Mount a volume to access the folder and run the test
    command: |
      docker pull loadimpact/k6:latest
      docker run -i -v $HOME/my-project:/ci:rw loadimpact/k6:latest run \
      --out json=/ci/results/full.json \
      --summary-export=/ci/results/summary.json \
      /ci/tests/local.js
      
version: 2
jobs:
  run_performance_tests:
    <<: *defaults
    # Use `machine` executor because the Docker executor cannot mount volumes
    machine: true
    steps:
      - checkout
      - *k6_performance_tests
      - store_artifacts:
          path: /results/

workflows:
  version: 2
  build-and-test:
    jobs:
      - run_performance_tests
