version: 2.1
orbs:
  k6io: k6io/test@1.1.0

workflows:
  load_test:
    jobs:
      - k6io/test:
          arguments: '--out json=./results/full.json --summary-export=./results/summary.json'
          script: tests/local.js
          post-steps:
            - store_test_results:
                path: ./results
            - store_artifacts:
                path: ./results
      