# For info: https://circleci.com/developer/orbs/orb/k6io/test
version: 2.1
orbs:
  k6io: k6io/test@1.1.0

workflows:
  load_test:
    jobs:
      - k6io/test:
          arguments: '--out json=./results/full.json --summary-export=./results/summary.json'
          script: tests/local.js
          # cloud: true
          # token: K6_CLOUD_TOKEN
          post-steps:
            - store_artifacts:
                path: ./results