# Configures Grafana to use InfluxDB as a data source, 
# using the hostname configured in docker-compose ‘influxdb’ 
# to connect to the database over the local docker network on port 8086.
apiVersion: 1

datasources:
  - name: k6influxdb
    type: influxdb
    access: proxy
    database: k6
    url: http://influxdb:8086
    isDefault: true
